### ISSUE TITLE
Adding a folder under a file is available as an option

### ISSUE THREAD

**Issue by kevin-david** [ALM-Rangers/Folder-Management-Extension#11]
This picture should sum it up:
![image](https://cloud.githubusercontent.com/assets/1923186/24004841/cb29170a-0a3d-11e7-9301-819a3997f0fb.png)

The extension makes this request to the `pushes` REST endpoint:
```
{
	"refUpdates": [{
		"name": "refs/heads/master",
		"oldObjectId": "01f4dcffdf4b0645862f659e94b94aea214fc324"
	}],
	"commits": [{
		"comment": "Added new folder",
		"changes": [{
			"changeType": "add",
			"item": {
				"path": "/test/_placeHolderFile.md/NewFolder/_placeHolderFile.md"
			},
			"newContent": {
				"content": "Git placeholder file",
				"contentType": "rawtext"
			}
		}]
	}]
}
```

which gets this (snipped) response:
```
{
	"message": "The path actions supplied tried to change the type of a blob to a tree, which is not supported.\r\nParameter name: newPush",
	"typeKey": "InvalidArgumentValueException",
}
```

Which makes sense - you can't add a tree under a blob :)

**Comment by wpschaub** [comment]
Thank you for troubleshooting this issue. We're not planning any feature updates for this deprecated extension, but would welcome any PR to help us improve the sample.
