### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by gdiazderadaa** [ALM-Rangers/Folder-Management-Extension#12]
Hi there,

I've tried to install the extension but got a Failed Installation message:

> The installation was unable to install the extension to all the select products. For more information, click on the install log at the bottom of the dialog. This extension is not available on any current installed products.

The log shows the following info:

> 3/28/2017 4:43:01 AM - Searching for applicable products...
3/28/2017 4:43:01 AM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
3/28/2017 4:43:01 AM - Found installed product - Microsoft Visual Studio Community 2015
3/28/2017 4:43:01 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
3/28/2017 4:43:01 AM - Found installed product - Global Location
3/28/2017 4:43:01 AM - Found installed product - ssms
3/28/2017 4:43:01 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

However Team Foundation Server 2015 Update 3 is installed on the server.

Any thoughts?

**Comment by wpschaub** [comment]
It looks like you're trying to install the Team Services / TFS extension in Visual Studio IDE, which is not supported. See https://www.visualstudio.com/en-us/docs/marketplace/get-vsts-extensions for Team Services and https://www.visualstudio.com/en-us/docs/marketplace/get-tfs-extensions for TFS on-prem.

**Comment by gdiazderadaa** [comment]
No, I'm trying to install it in the server where TFS 2015 is installed...

⁣Enviado desde BlueMail ​

**Comment by wpschaub** [comment]
How are you trying to install the extension on the server? Are you following these instructions https://www.visualstudio.com/en-us/docs/marketplace/get-tfs-extensions for TFS on-prem?

**Comment by gdiazderadaa** [comment]
Sorry, I haven't installed an extension before and didn't know the procedure. Installed and working no. Thanks for your help
