### ISSUE TITLE
Update extension icon

### ISSUE THREAD

**Issue by willsmythe** [ALM-Rangers/Folder-Management-Extension#23]
Please update your extenion's icon with the provided icon from the Microsoft design team.

![market_foldermanagement_128x](https://user-images.githubusercontent.com/2503052/32660329-67a7392c-c5f0-11e7-97a9-59aec54b7ebc.png)

Also remove any "branding" attributes (i..e. use the default gray brand color).

**Comment by wpschaub** [comment]
@willsmythe we updated the icon as requested, but left the theme as icon blends into it nicely. Anything else we need to update?
![2017-11-11_10-04-22](https://user-images.githubusercontent.com/12176555/32692166-087de800-c6c8-11e7-80e0-8964c56b3b11.png)
