### ISSUE TITLE
On Prem TFS 2015 U3 Support

### ISSUE THREAD

**Issue by edwardwcorbett** [ALM-Rangers/Folder-Management-Extension#27]
I would really like to use this at my organization but they are refusing to update from on prem 2015 U3 to U4.  Is there anyway I can download a version compatible with U3? or what has changed that it is now not compatible with U3? Looking at previous reviews it appears to have worked with U3 in the past.

**Comment by WouterDeKort** [comment]
@l00t3d,

I'm not sure what the reason was we don't support 2015.3 anymore. Have you tried the extension? Do you get any errors?

I'll look into it and get back to you.

Wouter

**Comment by edwardwcorbett** [comment]
@WouterDeKort 

Thanks for checking, I have not tried the extension.  I only saw on the Visual Studio Market place that the oldest version it works with is Team Foundation Server 2015 update 4.  We don't have a test environment for our TFS deployment.  With about 200 active users I am hesitant to install it if it's going to cause an issue for everyone.

**Comment by WouterDeKort** [comment]
Hi @l00t3d,

I've done a quick test and the extension seems to work with 15.3. I would suggest you give it a try. If you run into errors just let me know.

Thanks,
Wouter
